version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./api
    env_file: ./api/.env
    ports:
      - "5000:5000"
    networks:
      - mevn
    command: ["npm", "start"]

  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - mevn

  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "3000:3000"

networks:
  mevn:
