db = db.getSiblingDB(process.env.MONGO_INITDB_DATABASE);

db.createUser({
  user: process.env.MONGO_USER,
  pwd: process.env.MONGO_PASSWORD,
  roles: [
    {
      role: "readWrite",
      db: process.env.MONGO_INITDB_DATABASE,
    },
  ],
});

db.createCollection("users");
db.users.insertMany([
  {
    _id: ObjectId("60f4b6e1e9f0f4001f6b3b4f"),
    name: "LeGrizzly",
    email: "LeGrizzly@hotmail.fr",
    password: "$2a$10$HdhL0Nwy2AQrAwyVxQ9HMuhpz5cgczdhrRPY4ePCh.gseXHniOYvS", // password: "LeGrizzly@hotmail.fr"
    role: "ROLE_ADMIN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Horotopia",
    email: "guirado.leo@gmail.com",
    password: "$2y$10$YQgt4OqsN4VgY67W.9xBkeGdEXBeeCRID8TBMjN2.vNbpL0IftGn2", // password: "guirado.leo@gmail.com"
    role: "ROLE_USER",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: ObjectId("60f4b6e1e9f0f4001f6b3b51"),
    name: "Jane Doe",
    email: "fake2@mail.com",
    password: null,
    role: "ROLE_USER",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: ObjectId("60f4b6e1e9f0f4001f6b3b52"),
    name: "Alice Smith",
    email: "alice@mail.com",
    password: null,
    role: "ROLE_USER",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: ObjectId("60f4b6e1e9f0f4001f6b3b53"),
    name: "Bob Johnson",
    email: "bob@mail.com",
    password: null,
    role: "ROLE_USER",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]);

db.createCollection("product");
db.product.insertMany([
  {
    _id: ObjectId("60f4b6e1e9f0f4001b111111"),
    name: "Bulbizarre",
    description: "Bulbizarre est un Pokémon de type Plante et Poison, connu pour la graine qu’il porte sur son dos. Cette graine grandit avec lui et stocke de l’énergie solaire, ce qui lui permet d’utiliser de puissantes attaques de type Plante, comme Fouet Lianes ou Vampigraine. Bulbizarre est souvent vu en train de se reposer au soleil pour alimenter cette graine en énergie. Sa nature calme et son attachement à son dresseur en font un excellent compagnon pour les débutants.",
    habitat: "Bulbizarre préfère les prairies et les forêts denses où il peut se cacher parmi la végétation. Il s’installe souvent dans des zones ensoleillées pendant la journée pour absorber l’énergie solaire nécessaire à la graine sur son dos. La nuit, Bulbizarre dort dans des nids de feuilles ou de mousse, souvent à l’ombre des arbres pour rester camouflé. Ces abris naturels offrent à Bulbizarre la tranquillité et la sécurité dont il a besoin pour se reposer pleinement.",
    habitude: "Bulbizarre est un Pokémon calme et méthodique qui tire son énergie du soleil. Il passe de longues heures à se reposer dans des clairières ensoleillées, absorbant la lumière grâce à la graine sur son dos, qui agit comme une source d’énergie interne. Il se nourrit principalement de feuilles, de baies et de racines qu’il trouve en utilisant ses lianes. Bien que peu agressif, Bulbizarre s’entraîne régulièrement à utiliser ses capacités de type Plante, comme Vampigraine ou Fouet Lianes, pour rester en forme. La nuit, il dort profondément dans des herbes hautes ou des abris naturels, souvent entouré d’autres Pokémon, car il apprécie la compagnie pour se sentir en sécurité.",
    type: "plante",
    evolutionLevel: 1,
    evolutionReference: "Herbizarre",
    weight: 6900,
    height: 70,
    age: 5,
    price: 40000,
    category: "pokémon",
    stock: 8,
  },
  {
    _id: ObjectId("60f4b6e1e9f0f4001b111112"),
    name: "Salamèche",
    description: "Salamèche est un Pokémon de type Feu de la première génération. Reconnaissable à sa petite taille, sa peau orange et la flamme qui brûle constamment au bout de sa queue, Salamèche est connu pour sa nature amicale mais ardente. La flamme de sa queue reflète son état émotionnel : elle vacille doucement quand il est calme et brûle intensément lorsqu’il est en colère. Salamèche évolue en Reptincel puis en Dracaufeu.",
    habitat: "Salamèche aime les zones rocheuses ou volcaniques, où il peut profiter de la chaleur naturelle. Il dort souvent dans des grottes ou sous des surplombs rocheux qui protègent sa flamme des intempéries. Ce Pokémon veille à ce que sa flamme reste toujours allumée, même en dormant, et il choisit donc des endroits où le vent est faible. Salamèche peut aussi se blottir contre des sources de chaleur pour se détendre et récupérer après une journée active.",
    habitude: "Salamèche est un Pokémon énergique et curieux qui vit souvent près de sources de chaleur naturelles comme des volcans ou des champs de lave. Il se nourrit principalement de baies, de fruits cuits par sa flamme, et de petits insectes. Son activité physique est intense : il aime courir, grimper et s’exercer à projeter des flammes. La flamme de sa queue est un indicateur constant de son humeur et de sa vitalité. Le soir, Salamèche cherche un lieu abrité où il peut se reposer en toute sécurité, comme une caverne ou un endroit protégé du vent. Sa flamme éclaire doucement les environs, dissuadant les prédateurs et créant une ambiance apaisante pendant son sommeil.",
    type: "feu",
    evolutionLevel: 1,
    evolutionReference: "Reptincel",
    weight: 8500,
    height: 60,
    age: 3,
    price: 45001,
    category: "pokémon",
    stock: 10,
  },
  {
    _id: ObjectId("60f4b6e1e9f0f4001b111113"),
    name: "Carapuce",
    description: "Carapuce est un Pokémon de type Eau de petite taille, reconnaissable à sa carapace dure et brillante. Lorsqu'il se sent menacé, il peut rentrer entièrement dans sa carapace pour se protéger des attaques ennemies. Il est capable de projeter de puissants jets d'eau à haute pression pour repousser ses adversaires ou éteindre des incendies. Carapuce est un compagnon fidèle et plein d'énergie, apprécié pour son courage et son esprit joueur. Il évolue en Carabaffe, puis en Tortank.",
    habitat: "Carapuce préfère vivre dans des environnements aquatiques comme des rivières, des lacs ou des étangs calmes. Il se loge souvent dans des zones peu profondes où il peut facilement accéder à la terre ferme pour se reposer. La nuit, Carapuce se protège en dormant partiellement immergé, avec juste sa carapace visible, ce qui lui offre un camouflage naturel contre les prédateurs. En cas de menace, il se cache dans sa carapace, une véritable forteresse mobile.",
    habitude: "Carapuce vit dans des environnements aquatiques comme les lacs, les rivières ou les plages, où il se sent le plus à l’aise. Il est omnivore, se nourrissant principalement de petits poissons, d’algues et parfois d’insectes aquatiques. Pour trouver sa nourriture, il plonge souvent sous l'eau, utilisant ses puissantes pattes palmées pour nager rapidement. Son activité physique est variée : il alterne entre des périodes de nage active, des jeux aquatiques et des entraînements où il perfectionne son jet d’eau à haute pression. Lorsqu'il est fatigué, Carapuce aime s’exposer au soleil sur des rochers ou la berge, sa carapace absorbant une partie de la chaleur pour réguler sa température. La nuit, il dort dans des cavités rocheuses ou sur des fonds sablonneux, rentrant entièrement dans sa carapace pour se protéger des prédateurs.",
    type: "eau",
    evolutionLevel: 1,
    evolutionReference: "Carabaffe",
    weight: 9000,
    height: 50,
    age: 4,
    price: 42000,
    category: "pokémon",
    stock: 7,
  },
  {
    _id: ObjectId("60f4b6e1e9f0f4001b111114"),
    name: "Roucool",
    description: "Roucool est un Pokémon de type Normal et Vol connu pour sa nature discrète et prudente. Ce petit oiseau préfère éviter les conflits en se cachant dans les hautes herbes ou en s'envolant rapidement. Malgré sa petite taille, Roucool est un excellent éclaireur grâce à sa vue perçante. Lorsqu'il est menacé, il peut battre des ailes pour projeter des nuages de poussière et aveugler ses ennemis. Avec de l'entraînement, il évolue en Roucoups, puis en Roucarnage, un puissant prédateur aérien.",
    habitat: "Roucool niche généralement dans les branches des arbres ou dans les hautes herbes des prairies. Il préfère des endroits discrets et bien cachés pour éviter les prédateurs. Ses nids sont faits de brindilles et de feuilles, lui offrant un abri confortable et sûr. Pendant la nuit, il dort dans ces refuges naturels, toujours prêt à s'envoler au moindre bruit suspect grâce à sa nature prudente.",
    habitude: "Roucool est un Pokémon diurne qui préfère les zones ouvertes avec de hautes herbes, des forêts clairsemées ou des collines. Son régime alimentaire se compose principalement de graines, de baies et parfois de petits insectes. Il utilise son bec précis et ses pattes agiles pour extraire des aliments dans des endroits difficiles d'accès. Ce petit oiseau est constamment en mouvement, effectuant des vols courts mais fréquents pour surveiller son territoire et éviter les prédateurs. Roucool est également un expert en camouflage, se dissimulant dans les feuillages ou les buissons lorsqu’il sent le danger. Il dort profondément la nuit, niché dans des branches ou des crevasses, où il est hors de portée des prédateurs terrestres.",
    type: "vol",
    evolutionLevel: 1,
    evolutionReference: "Roucoups",
    weight: 1800,
    height: 30,
    age: 2,
    price: 15001,
    category: "pokémon",
    stock: 15,
  },
  {
    _id: ObjectId("60f4b6e1e9f0f4001b111115"),
    name: "Goupix",
    description: "Goupix est un Pokémon de type Feu, distingué par sa fourrure orange soyeuse et ses queues élégantes. À sa naissance, il n'a qu'une seule queue, mais celle-ci se divise en plusieurs au fil de sa croissance. Goupix est connu pour sa grâce et son intelligence. Il peut produire des flammes d'une chaleur intense pour se défendre ou intimider ses ennemis. En évoluant grâce à une Pierre Feu, Goupix devient Feunard, un Pokémon majestueux et énigmatique.",
    habitat: "Goupix s'installe souvent dans des endroits chauds comme des collines ensoleillées ou des forêts proches de sources thermales. Il se creuse des tanières peu profondes dans le sol ou utilise des cavités naturelles pour se protéger du froid et des intrus. Ses tanières sont souvent tapissées de mousse ou de fourrure perdue, offrant un endroit douillet où dormir. Goupix aime aussi se reposer près de foyers ou de feux de camp lorsqu’il est en compagnie de son dresseur.",
    habitude: "Goupix est un Pokémon crépusculaire, plus actif lorsque la lumière du jour faiblit. Il se nourrit d’un mélange de baies sucrées, de fruits mûrs, et de petits mammifères qu’il chasse avec une précision impressionnante. Sa fourrure soyeuse et ses queues élégantes nécessitent un entretien méticuleux, et Goupix consacre du temps à se toiletter quotidiennement. Lorsqu’il n’est pas en chasse ou en exploration, il s’entraîne à contrôler ses flammes en lançant de petites boules de feu sur des cibles naturelles comme des pierres ou des arbres. Son sommeil est stratégique : il choisit des lieux chauds comme des grottes volcaniques ou des terriers secs, où il peut s’enrouler autour de lui-même, ses queues protégeant son corps du froid.",
    type: "feu",
    evolutionLevel: 1,
    evolutionReference: "Feunard",
    weight: 990,
    height: 60,
    age: 3,
    price: 35001,
    category: "pokémon",
    stock: 6,
  },
  {
    _id: ObjectId("60f4b6e1e9f0f4001b111116"),
    name: "Rondoudou",
    description: "Rondoudou est un Pokémon de type Normal et Fée célèbre pour sa voix mélodieuse. Lorsqu'il chante, il émet une mélodie si apaisante qu'elle endort instantanément quiconque l'écoute, y compris ses adversaires en combat. Sa forme ronde et ses grands yeux pétillants le rendent irrésistiblement mignon. Bien qu'il soit doux et amical, Jigglypuff peut être assez rancunier si on ignore son chant. Il évolue en Rondoudou grâce à une Pierre Lune.",
    habitat: "Rondoudou recherche des environnements tranquilles et sécurisés comme des clairières ombragées ou des cavernes peu fréquentées. Il construit souvent son nid dans des endroits moelleux, utilisant des feuilles, des plumes ou même des objets trouvés pour créer une surface confortable. La nuit, il aime s’endormir en chantant doucement pour se bercer. Sa forme ronde lui permet de se blottir dans des espaces confinés, augmentant son sentiment de sécurité.",
    habitude: "Rondoudou mène une vie paisible et détendue, où la recherche de confort est prioritaire. Il se nourrit principalement de baies juteuses et sucrées, et apprécie particulièrement les fruits rares qu’il peut trouver grâce à son ouïe fine. Peu actif physiquement, il passe ses journées à chanter pour le plaisir ou à s’entourer d’autres Pokémon qui aiment sa compagnie apaisante. Son chant est si efficace pour endormir qu’il n’a presque jamais besoin de fuir les conflits. Lorsqu'il dort, ce Pokémon choisit des endroits doux et moelleux, comme des clairières herbeuses ou des lits de mousse, où il peut s’enfoncer pour un sommeil réparateur. Il est connu pour faire des rêves paisibles qui renforcent son énergie.",
    type: "fée",
    evolutionLevel: 1,
    evolutionReference: "Grosdoudou",
    weight: 550,
    height: 50,
    age: 4,
    price: 20000,
    category: "pokémon",
    stock: 20,
  },
  {
    _id: ObjectId("60f4b6e1e9f0f4001b111117"),
    name: "Mélofée",
    description: "Mélofée est un Pokémon de type Fée souvent associé à la lune et aux étoiles. Ce petit Pokémon magique est connu pour sa nature joyeuse et curieuse. On dit qu'il danse sous la lumière de la lune dans des lieux secrets. Sa capacité à absorber la lumière lunaire et à utiliser des pouvoirs mystérieux fascine les dresseurs. Mélofée est aussi très affectueux et devient rapidement attaché à son dresseur. Il évolue en Mélodelfe grâce à une Pierre Lune.",
    habitat: "Mélofée adore les montagnes et les collines où la lumière de la lune est visible. Il se loge dans des cavernes ou des crevasses rocheuses, souvent en groupe, créant des habitats collectifs où il peut se sentir en sécurité. Ces lieux sont souvent tapissés de poussière stellaire qu’il semble collecter instinctivement. Mélofée dort en cercle avec ses congénères, profitant de l'énergie lunaire pour se revitaliser.",
    habitude: "Mélofée est un Pokémon nocturne et mystérieux qui adore les environnements calmes et isolés, comme les montagnes ou les clairières lumineuses. Il se nourrit principalement de baies lumineuses et de nectar, mais il apprécie aussi les champignons rares qu’il déniche grâce à son odorat. La nuit, Mélofée se rassemble souvent avec d’autres Pokémon de son espèce pour des danses sous la lune, un rituel qui semble amplifier son énergie magique. Pendant ces danses, il absorbe l’énergie lunaire, qu'il stocke dans son corps pour l'utiliser en cas de besoin. Après ces rituels, il dort profondément dans des recoins sombres et sécurisés, souvent à l’intérieur de petites cavernes. Son sommeil est long et réparateur, indispensable pour régénérer sa puissance magique.",
    type: "fée",
    evolutionLevel: 1,
    evolutionReference: "Mélodelfe",
    weight: 750,
    height: 60,
    age: 3,
    price: 25001,
    category: "pokémon",
    stock: 18,
  },
  {
    _id: ObjectId("60f4b6e1e9f0f4001b111118"),
    name: "Fantominus",
    description: "Fantominus est un Pokémon de type Spectre et Poison, composé presque entièrement de gaz toxique. Il peut se rendre invisible et traverser les murs, ce qui le rend très difficile à capturer. Malgré son apparence effrayante, Fantominus est joueur et adore effrayer ses cibles pour s’amuser. Ses attaques spectrales le rendent redoutable en combat, surtout face à ceux qui ne savent pas comment gérer un Pokémon fantôme. Avec de l'entraînement, il évolue en Spectrum, puis en Ectoplasma.",
    habitat: "Fantominus choisit des lieux sombres et isolés pour habiter, comme des tours abandonnées, des grottes ou des cimetières. Contrairement à d'autres Pokémon, il ne construit pas de nids ou d'abris fixes, préférant flotter librement dans son environnement. Pendant la journée, il se repose dans les coins les plus obscurs qu'il peut trouver, souvent suspendu à quelques centimètres du sol, invisible à l’œil nu.",
    habitude: "Fantominus mène une existence nocturne et insaisissable. N’ayant pas de corps solide, il se nourrit de manière unique : il absorbe l’énergie des émotions humaines ou Pokémon, en particulier la peur. Très joueur, il passe ses nuits à flotter silencieusement dans les ombres, s’amusant à surprendre les passants ou à espionner les lieux animés. Sa capacité à devenir invisible et à traverser les murs lui permet d’explorer des endroits inaccessibles. La journée, il se retire dans des lieux sombres et humides, comme des caves ou des vieilles tours, où il entre dans un état de sommeil léger. Ce repos est entrecoupé de moments où il se dissipe dans l’air pour se protéger des éventuels dangers.",
    type: "spectre",
    evolutionLevel: 1,
    evolutionReference: "Spectrum",
    weight: 1,
    height: 130,
    age: 6,
    price: 30000,
    category: "pokémon",
    stock: 12,
  },
  {
    _id: ObjectId("60f4b6e1e9f0f4001b111119"),
    name: "Machoc",
    description: "Machoc est un Pokémon de type Combat au corps musclé. Toujours en quête de force, il passe son temps à s'entraîner pour développer ses capacités physiques. Il est capable de soulever des objets bien plus lourds que lui sans effort apparent. Machoc rêve de devenir un combattant inégalé et participe souvent à des combats amicaux pour s'améliorer. Avec de l'entraînement, il évolue en Machopeur, puis en Mackogneur, un véritable colosse.",
    habitat: "Machoc vit dans des zones rocheuses ou montagneuses, où il peut trouver des endroits stables pour s'entraîner. Il construit souvent des abris rudimentaires en empilant des rochers pour créer un espace protégé contre les intempéries. La nuit, Machoc dort profondément sur des surfaces dures, utilisant parfois des pierres plates comme lits. Son environnement est toujours proche de son terrain d’entraînement, car il aime optimiser chaque moment pour développer sa force.",
    habitude: "Machoc est un modèle de discipline et d’endurance. Ce Pokémon passe presque toute sa journée à s’entraîner, soulevant des pierres, courant sur des terrains accidentés, ou exécutant des séries de coups pour perfectionner sa technique de combat. Son alimentation est riche en protéines : il consomme des baies énergétiques, des noix, et parfois de la viande. Sa routine stricte inclut également des étirements et des exercices de méditation pour améliorer sa concentration. Bien qu’il soit actif toute la journée, il respecte un cycle de sommeil rigoureux pour permettre à ses muscles de récupérer. Machoc dort souvent dans des grottes fraîches ou sous des arbres, où il peut s'étendre confortablement après une journée d'efforts.",
    type: "combat",
    evolutionLevel: 1,
    evolutionReference: "Machopeur",
    weight: 19500,
    height: 80,
    age: 4,
    price: 38000,
    category: "pokémon",
    stock: 9,
  },
  {
    _id: ObjectId("60f4b6e1e9f0f4001b111120"),
    name: "Évoli",
    description: "Évoli est un Pokémon de type Normal très spécial, connu pour son incroyable capacité d'adaptation. Sa composition génétique instable lui permet de s’adapter à divers environnements et de changer de forme en conséquence. Grâce à des pierres évolutives ou des conditions spécifiques, Évoli peut évoluer en plusieurs Pokémon, chacun ayant des types et capacités uniques, comme Aquali (Eau), Voltali (Électrique), ou Pyroli (Feu). Ce Pokémon curieux et sociable est un favori des dresseurs.",
    habitat: "Évoli s’adapte à une grande variété d’habitats, que ce soit dans des forêts, des plaines ou même des zones urbaines. Il préfère les abris naturels comme des creux d’arbres, des buissons denses ou des coins chauds dans des bâtiments. Lorsqu'il dort, Évoli cherche un endroit sûr et isolé, souvent en hauteur ou caché pour se protéger des prédateurs. Son adaptabilité exceptionnelle lui permet de trouver refuge dans presque tous les environnements.",
    habitude: "Évoli est un Pokémon adaptable, capable de vivre dans presque tous les environnements grâce à sa composition génétique unique. Il explore son territoire avec curiosité, cherchant des fruits, des baies, et parfois des champignons pour se nourrir. Son activité physique inclut des courses rapides et des jeux avec d’autres Pokémon, ce qui l’aide à maintenir sa souplesse et son endurance. Très sociable, Évoli aime interagir avec ses dresseurs et les autres Pokémon, ce qui le rend facile à entraîner. Le soir, il trouve un abri naturel comme un terrier ou un nid improvisé, et son sommeil est léger, car il est toujours prêt à réagir en cas de danger.",
    type: "normal",
    evolutionLevel: 1,
    evolutionReference: "plusieurs évolutions possibles",
    weight: 6500,
    height: 30,
    age: 3,
    price: 60000,
    category: "pokémon",
    stock: 5,
  },
]);

db.createCollection("address");
db.address.insertMany([
  {
    street: "1 rue de la paix",
    city: "Paris",
    postalCode: "75001",
    country: "France",
    userId: ObjectId("60f4b6e1e9f0f4001f6b3b4f"),
  },
  {
    street: "2 rue de la liberté",
    city: "Lyon",
    postalCode: "69000",
    country: "France",
    userId: ObjectId("60f4b6e1e9f0f4001f6b3b50"),
  },
  {
    street: "3 rue de la fraternité",
    city: "Marseille",
    postalCode: "13000",
    country: "France",
    userId: ObjectId("60f4b6e1e9f0f4001f6b3b51"),
  },
  {
    street: "4 rue de l'égalité",
    city: "Bordeaux",
    postalCode: "33000",
    country: "France",
    userId: ObjectId("60f4b6e1e9f0f4001f6b3b52"),
  },
  {
    street: "5 rue de la justice",
    city: "Lille",
    postalCode: "59000",
    country: "France",
    userId: ObjectId("60f4b6e1e9f0f4001f6b3b53"),
  },
]);

db.createCollection("orders");
db.orders.insertMany([
  {
    userId: ObjectId("60f4b6e1e9f0f4001f6b3b4f"),
    items: [
      {
        productId: ObjectId("60f4b6e1e9f0f4001b111111"),
        quantity: 2,
        price: 80000,
      },
      {
        productId: ObjectId("60f4b6e1e9f0f4001b111112"),
        quantity: 1,
        price: 45001,
      },
    ],
    totalAmount: 125001,
    status: "completed"
  },
  {
    userId: ObjectId("60f4b6e1e9f0f4001f6b3b50"),
    items: [
      {
        productId: ObjectId("60f4b6e1e9f0f4001b111113"),
        quantity: 3,
        price: 126000,
      },
    ],
    totalAmount: 126000,
    status: "pending"
  },
  {
    userId: ObjectId("60f4b6e1e9f0f4001f6b3b53"),
    items: [
      {
        productId: ObjectId("60f4b6e1e9f0f4001b111111"),
        quantity: 1,
        price: 35001,
      },
      {
        productId: ObjectId("60f4b6e1e9f0f4001b111114"),
        quantity: 2,
        price: 70002,
      },
    ],
    totalAmount: 105003,
    status: "cancelled"
  },
  {
    userId: ObjectId("60f4b6e1e9f0f4001f6b3b51"),
    items: [
      {
        productId: ObjectId("60f4b6e1e9f0f4001b111116"),
        quantity: 4,
        price: 180004,
      },
    ],
    totalAmount: 180004,
    status: "completed"
  },
  {
    userId: ObjectId("60f4b6e1e9f0f4001f6b3b4f"),
    items: [
      {
        productId: ObjectId("60f4b6e1e9f0f4001b111117"),
        quantity: 2,
        price: 80000,
      },
      {
        productId: ObjectId("60f4b6e1e9f0f4001b111118"),
        quantity: 1,
        price: 35001,
      },
    ],
    totalAmount: 115001,
    status: "pending"
  },
]);
